/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
suma_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = arg1 + arg2;

	return &result;
}

float *
resta_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	result = arg1 - arg2;

	return &result;
}

float *
mult_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = arg1 * arg2;

	return &result;
}

float *
div_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = arg1 / arg2;

	return &result;
}
