/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calculadora_1(char *host, float arg1, char op, float arg2)
{
	CLIENT *clnt;
	float  *result;
	

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORAVER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if(arg2 == 0 && op == '/'){
		printf("Se esta sucediendo algun tipo de error\n");
		return -1;
	}
	switch (op)
	{
	case '+':
		result = suma_1(arg1, arg2, clnt);
		if (result == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;
	
	case '-':
		result = resta_1(arg1, arg2, clnt);
		if (result == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;

	case 'x':
		result = mult_1(arg1, arg2, clnt);
		if (result == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;

	case '/':
		result = div_1(arg1, arg2, clnt);
		if (result == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		break;
	
	default:
		printf("Se esta sucediendo algun tipo de error\n");
		break;
	}

	//Mostramos en pantalla el valor resultado
	printf("El valor resultado es %f\n", *result);

	//free(result);
	

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 5) {
		printf ("usage: %s server_host arg1 operator arg2\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	float arg1 = atof(argv[2]);
	char op = argv[3][0];
	printf("%c\n", op);
	float arg2 = atof(argv[4]);
	
	calculadora_1 (host, arg1, op, arg2);
exit (0);
}
